function fetchCroatian() {
        var topTrans = document.getElementById("toptrns");
        var aboutTrans = document.getElementById("abouttrns");
        var portfolioTrans = document.getElementById("porttrns");
        var contactTrans = document.getElementById("contacttrns");
        var coverTrans = document.getElementById("covertrns");
        var introTrans = document.getElementById("introtrns");
        var projectTrans = document.getElementById("projecttrns");
        var interiartTrans = document.getElementById("interiarttrns");
        var interiLink = document.getElementById("interilink");
        var cybershopTrans = document.getElementById("cybershoptrns");
        var cyberLink = document.getElementById("cyberlink");
        var weatherTrans = document.getElementById("weathertrns");
        var weatherLink = document.getElementById("weatherlink");
        var todoTrans = document.getElementById("todotrns");
        var todoTitle = document.getElementById("todonaslov");
        var todoLink = document.getElementById("todolink");
        var oblutakTrans = document.getElementById("oblutaktrns");
        var oblutakTitle = document.getElementById("oblutaknaslov");
        var oblutakLink = document.getElementById("oblutaklink");
        var infoTrans = document.getElementById("infotrns");
    
        topTrans.innerHTML = "Početak";
        aboutTrans.innerHTML = "O meni";
        portfolioTrans.innerHTML = "Portfolio";
        contactTrans.innerHTML = "Kontakt";
        coverTrans.innerHTML = "Dobrodošli u moj portfolio!";
        introTrans.innerHTML = '<p class="h2 my-other-font"><b>Anamaria Živković</b>, <span class="h3 my-other-font">mag. psych.</span></p><p class="h3 my-font">Full stack developer in training</p><p class="h4 my-font"><b>Naučene vještine:</b></p><ul class="h5 my-font"><li> HTML</li> <li> CSS</li> <li> Bootstrap</li> <li> JavaScript</li> <li> jQuery</li></ul><p class="h4 my-font"><b>Datum rođenja:</b> 27/06/1993</p><p class="h4 my-font"><b>Mjesto stanovanja:</b> Šibenik, Hrvatska</p>';
        projectTrans.innerHTML = "Moji projekti";
        interiartTrans.innerHTML = "Internetska stranica posvećena izmišljenoj tvrtci za dizajn interijera. Fokus je na estetici, a uključuje sekcije o tvrtci, uslugama koje pruža i kontakt formu";
        cybershopTrans.innerHTML = "Primjer webshopa usmjerenog na prodaju stolnih računala, laptopa, mobitela, konzola i druge elektronske opreme. Uključuje i funkcionalnu košaricu.";
        weatherTrans.innerHTML = "Aplikacija koja pruža pregled trenutne temperature, osjeta, vremenskih prilika i vjetra za bilo koji grad koji unesete. Postoji i mogućnost spremanja omiljenih lokacija.";
        todoTrans.innerHTML = "To-do lista u koju se mogu slobodno unositi i brisati stavke. Stavke ostaju zapamćene i na refresh stranice.";
        todoTitle.innerHTML = "Moja to-do lista";
        oblutakTrans.innerHTML = "Stranica o prodaji ukrasnih oblutaka, izrađena uz pomoć Bootstrapa.";
        oblutakTitle.innerHTML = "Ukrasni oblutak";
        interiLink.innerHTML = "Posjeti stranicu!";
        cyberLink.innerHTML = "Posjeti stranicu!";
        weatherLink.innerHTML = "Posjeti stranicu!";
        todoLink.innerHTML = "Posjeti stranicu!";
        oblutakLink.innerHTML = "Posjeti stranicu!";
        infoTrans.innerHTML = "Kontaktiraj me!";
    }